// apis
export const TOPIC_LIST = '/api/topic/list.json'
export const FRIEND_LIST = '/api/friend/list.json'
export const AUTHOR_NAME = '/api/author/name.json'
export const FOOTER_ICON_LIST = '/api/footer/icon/list.json'
export const TAG_LIST = '/api/tag/list.json'
export const BLOG_LIST = '/api/blog/list.json'
export const BLOG_DETAIL = (id) => (`/api/blog/detail/${id}.json`)
export const ADMIN_LOGIN = 'http://localhost:5000/api/admin/login'
export const TAG_LIST_ADD = 'http://localhost:5000/api/admin/mock-post'
export const TAG_LIST_DELETE = 'http://localhost:5000/api/admin/mock-post'
export const TAG_LIST_UPDATE = 'http://localhost:5000/api/admin/mock-post'
export const FRIEND_LIST_ADD = 'http://localhost:5000/api/admin/mock-post'
export const FRIEND_LIST_DELETE = 'http://localhost:5000/api/admin/mock-post'
export const FRIEND_LIST_UPDATE = 'http://localhost:5000/api/admin/mock-post'
export const PINNED_LIST_ADD = 'http://localhost:5000/api/admin/mock-post'
export const PINNED_LIST_DELETE = 'http://localhost:5000/api/admin/mock-post'
export const PINNED_LIST_UPDATE = 'http://localhost:5000/api/admin/mock-post'
export const BLOG_DELETE = 'http://localhost:5000/api/admin/mock-post'
export const BLOG_CREATE = 'http://localhost:5000/api/admin/mock-post'
export const CV_URL = 'https://drive.google.com/file/d/1ot1pOLz1Eokr7z7C841Z5AAgnfoI9luq/view?usp=sharing'